# Generated by Django 5.0.6 on 2024-06-28 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus', '0001_initial'),
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bus')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.horario')),
            ],
        ),
    ]
