# Generated by Django 5.0.6 on 2024-07-23 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
        migrations.AlterModelOptions(
            name='journey',
            options={},
        ),
        migrations.RenameField(
            model_name='journeydriver',
            old_name='journay',
            new_name='journey',
        ),
        migrations.AddField(
            model_name='driver',
            name='bus',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.bus'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='driver',
            name='date_of_birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='date_of_birthday',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
