# Generated by Django 5.0.6 on 2024-07-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_journey_options_alter_bus_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='date_of_birthday',
            field=models.DateField(),
        ),
    ]
