# Generated by Django 5.0.6 on 2024-08-04 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='app.seat'),
        ),
    ]
