# Generated by Django 5.0.6 on 2024-07-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_passenger_date_of_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='date_of_birthday',
            field=models.DateField(),
        ),
    ]
