# Generated by Django 5.0.6 on 2024-08-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ticket_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeydriver',
            name='sold_capacity',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
