# Generated by Django 5.0.6 on 2024-07-16 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_driver_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.bus', unique=True),
        ),
    ]
