# Generated by Django 5.0.6 on 2024-08-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_journeydriver_sold_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journeydriver',
            name='sold_capacity',
        ),
    ]
