# Generated by Django 5.0.6 on 2024-07-16 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_driver_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='bus',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.bus'),
        ),
    ]
