# Generated by Django 5.0.6 on 2024-07-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_driver_bus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journeydriver',
            old_name='journay',
            new_name='journey',
        ),
    ]
